### ISSUE TITLE
Add rationing instrument to demand blocks

### ISSUE THREAD

**Issue by davidanthoff** [julia-mpsge/MPSGE.jl#100]

**Comment by EliLazarus** [comment]
I think this is done with an Auxilliary Variable in Endowments.

**Comment by mitchphillipson** [comment]
This is exactly correct. MPSGE.GAMS can't handle variables in quantities (or something) so the `R:` field is necessary. There are a couple more things like this too.

**Comment by mitchphillipson** [comment]
I would close this in favor of #152

**Comment by EliLazarus** [comment]
Agreed.
