### ISSUE TITLE
Provide a convenient way to extract solution values from the model

### ISSUE THREAD

**Issue by davidanthoff** [julia-mpsge/MPSGE.jl#12]
Right now one has to essentially query the underlying `JuMP.Model`, but we should provide some higher-level interface for that.

**Comment by mitchphillipson** [comment]
One option is JuMP-like access to Sectors, Commodities, etc. As an example in a model such as:

```
using MPSGE

M = Model()

@sector(M, X)
```

I find myself trying to use M[:X] to access X. Perhaps a reference to a object dictionary, which is exactly what JuMP does, to extract the sector reference.

Perhaps a solution is to add a variable reference to Sector. I'm using SectorRef here, but this may not be the correct location

```
struct SectorRef
    model
    index::Int
    subindex::Any
    subindex_names::Any
    jump_var::JuMP.VariableRef
    function SectorRef(model, index::Int, subindex::Any, subindex_names::Any) 
        return new(model, index, subindex, subindex_names, nothing)
    end
end

function add!(m::Model, s::ScalarSector)
    m._jump_model = nothing
    push!(m._sectors, s)
    m.obj_dict[s.name] = s #something like this
    return SectorRef(m, length(m._sectors), nothing, nothing)
end
```

And when you build the model, attach the corresponding JuMP variable to the specific sector. There are issues here, for example adding a Sector you'd need to reset all the references in each Sector, but that's a simple function iterating over the created dictionary if the _jump_model is not nothing.

**Comment by mitchphillipson** [comment]
I think this is now done. `value` works on MPSGE variables.

**Comment by EliLazarus** [comment]
Yes, totally good, fantastic! 
I'm still interested in being able to call the values of nested variables, but that's a small sub-issue and low priority.
