### ISSUE TITLE
Change type structure for Indexed* and Scalar*

### ISSUE THREAD

**Issue by davidanthoff** [julia-mpsge/MPSGE.jl#128]
Two types, ScalarSector and IndexedSector. IndexedSector is a container of ScalarSectors

```
mutable struct ScalarSector
    #name::Symbol #I don't think this needs to know it's own name, actually it may
    benchmark::Float64
    lower_bound::Float64
    upper_bound::Float64
    description::String
    fixed::Bool

    function ScalarSector(; description::AbstractString="", lower_bound::Float64=0.0, upper_bound=10e100, benchmark::Float64=1., fixed=false)
        return new(name, benchmark, lower_bound, upper_bound, description, fixed)
    end
end

mutable struct IndexedSector
    #name::Symbol
    indices::Any #We should know the type
    description::String
    data::DenseAxisArray


    function IndexedSector(#name::Symbol,
                           indices; 
                           description::AbstractString="",  
                           benchmark::Float64=1., 
                           lower_bound::Float64=0.0, 
                           upper_bound::Float64=10e100, 
                           fixed=false)

        return new(indices, description, DenseAxisArray(fill(ScalarSector(description,benchmark,lower_bound,upper_bound,fixed),length.(indices)),indices...)
    end
end
```

This eliminates the abstract type Sector, which you don't appear to be using outside of `model.jl`. However, this does currently duplicate the index set (it's also in the DenseAxisArray). After this define a getter to extract individual ScalarSectors from an IndexedSector. 

~~This would probably require a fairly substantial rewrite of code~~ I see odow has a pull request #124 removing eval from building variables. It's very easy to modify that code to make these changes, just modify `add_indexed_variable!`.

_Originally posted by @mitchphillipson in https://github.com/anthofflab/MPSGE.jl/issues/126#issuecomment-1708900880_

**Comment by mitchphillipson** [comment]
This is done

**Comment by EliLazarus** [comment]
I'll take your word on it. Well done.
