### ISSUE TITLE
Automatically calculate output values in Nests

### ISSUE THREAD

**Issue by EliLazarus** [julia-mpsge/MPSGE.jl#135]
In GAMS MPSGE, the inputs (in a nested input) have quantities and elasticities (of subsitution), but the user doesn't set the benchmark output. It's the sum of benchmark input, but can be tricky for the user to set with taxes etc, and adds another argument in the syntax, in fact it appears TWICE.
We should calculate it instead.

**Comment by mitchphillipson** [comment]
Done
