### ISSUE TITLE
Overhaul of ScalarDemand struct

### ISSUE THREAD

**Issue by mitchphillipson** [julia-mpsge/MPSGE.jl#153]
There are several issues with the ScalarDemand struct

1. The struct should be renamed Demand to match Production
2. The values for both final_demands and endowments dictionaries should be vectors with accessor functions which return the sum of the vector
3. The `@demand` macro should be reconsidered to take a single block, rather than separate blocks for final_demands and endowments.
4. The `raw_quantity` functions should return a float regardless of model status
5. endowments are stored as a dictionary of values. This should be dictionary of vectors to account for multiple endowments on the same commodity.

**Comment by EliLazarus** [comment]
PR #170 fixes this issue. We can close as soon as it's merged.
