### ISSUE TITLE
Check for and report data imbalance

### ISSUE THREAD

**Issue by EliLazarus** [julia-mpsge/MPSGE.jl#164]
Next level to #163 , check for all the source/sink value balances, to identify more precisely what is causing issues in the benchmark 0 iteration solve. I think margins are useful for that, but I _think_ a check and exception, or a report, or a function that checks on the values balancing to 0 for all variables in the model would be helpful to limit the troubleshooting needed.

- caveat: In a model with variables that are slack in the benchmark doesn't solve/has >0 margins with 0 iterations. Which suggests the need for warnings only, and options to turn off/ignore, or have as a separate function that doesn't interfere with build etc.

**Comment by mitchphillipson** [comment]
This would require the entire model be balanced every time, which isn't always true. 

What this really boils down to is "Check zero profit for each sector, market clearance for each commodity, and income balance for each consumer" which is exactly what solving at iteration limit zero does. The `generate_report` returns a DataFrame that you can use standard dataframe techniques to see non-zero marginal values.

**Comment by EliLazarus** [comment]
Makes sense. I guess it's just a piece for documentation: solve with zero iterations, generate_report, and sort by absolute margin values.
I kind of like the idea of a function to build it in, but maybe overkill.
