### ISSUE TITLE
Algebraic print output for compensated demand (and supply) is hard to read bc of the conditionals

### ISSUE THREAD

**Issue by EliLazarus** [julia-mpsge/MPSGE.jl#97]
The if else conditions, and especially the double in y_over_y_bar is printing every branch which makes it almost impossible to follow.

**Comment by mitchphillipson** [comment]
Yes. JuMP really needs a re-write in how it prints expressions. 

We should also consider a prettier printing of the model, with sums and such. I have a few ideas for this but they are little down the road.

**Comment by EliLazarus** [comment]
I think the specific issue in the title re the ifelses isn't a problem now.
So I'd close this, and keep #140 (Indexed (sum etc) printing would/will be an absolute coup and incredibly useful, high interest from users.). Ok?

**Comment by mitchphillipson** [comment]
Sounds good.

The printing can be much improved.
